### ISSUE TITLE
[KDE] No icon for Packet Tracer in Launcher

### ISSUE THREAD

**Issue by williamhatcher** [losuler/com.cisco.PacketTracer#15] opened 2023-05-06 02:25 UTC
![image](https://user-images.githubusercontent.com/24600763/236593679-f6e7b27d-c347-426b-b67e-6a42d0b30e11.png)

Not sure how to fix this myself as I've never built flatpacks before, but hopefully we can figure this out?

**Comment by losuler** [comment] 2023-05-13 19:00
Sorry, I can't reproduce this on Fedora 38 (KDE 5.27.4), as shown below. You'll have to provide me with more details about your setup (i.e. distro, KDE version, Packet Tracer version). It's possible this was fixed on a newer release of KDE (if you're running an older version of it).

![packet-tracer-kde](https://github.com/losuler/com.cisco.PacketTracer/assets/7016957/c3969a32-426f-48d0-ac49-305b966bf795)

**Comment by losuler** [comment] 2024-03-02 06:53
Closing this now as I wasn't able to reproduce the error. If you still have problems on a newer release of KDE, let me know.

**Closed as not planned by losuler** 2024-03-02 06:53 UTC
